name: check for bandit updates
on: {workflow_dispatch, schedule: [cron: '0 0 * * *']}
jobs:
  check-for-updates:
    runs-on: ubuntu-22.04
    name: check for bandit updates
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: x64
      - name: check version
        run: |
          pip install -U bandit
          pip freeze | grep 'bandit==' >requirements.txt
      - uses: peter-evans/create-pull-request@v3.10.0
        id: new_pull_request
        with:
          delete-branch: true
          title: automatic bandit update
          commit-message: automatic bandit update
          branch: automatic-bandit-update
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - if: steps.new_pull_request.outputs.pull-request-url != ''
        run: gh pr merge --auto --squash ${{ steps.new_pull_request.outputs.pull-request-url }}
